services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_HIKARI_JDBC_URL=jdbc:mariadb://db:3306/army?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_HIKARI_USERNAME=root
      - SPRING_DATASOURCE_HIKARI_PASSWORD=root123
      - FILE_UPLOAD_DIR=/app/uploads
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - army-network

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=army
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - army-network

networks:
  army-network:
    driver: bridge

volumes:
  mariadb_data:
  uploads_data:
